version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 99
    target-branch: 'dev'
    versioning-strategy: 'increase'

  - package-ecosystem: 'cargo'
    directory: '/packages/app/src-tauri'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 99
    target-branch: 'dev'
