name: Release

on:
  push:
    branches: [ dev ]

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      releaseId: ${{ steps.create_release.outputs.result }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      
      - name: Grab Changelog
          run: |
            CHANGELOG = $(awk -v ver=$(cat version.txt) '/^## / { if (p) { exit }; if ($2 == ver) { p=1; next} } p' changelog.md)
            echo "CHANGELOG<<EOF" >> $GITHUB_ENV
            echo "$CHANGELOG" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createRelease({
              tag_name: 'v0.6.1',
              name: 'v0.6.1',
              body: ${{ env.CHANGELOG }},
              draft: true,
              prerelease: false
            })

  b1:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - run: echo ${{needs.create_release.releaseId}}

#  build:
    

#  publish-release:
#    runs-on: 'ubuntu-latest'
