name: 'Release'

on:
  push:
    branches: [ 'dev' ]

jobs:
  create-release:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ env.VERSION }}
      changelog: ${{ env.CHANGELOG }}
      release_id: ${{ steps.create-release.outputs.result }}
    
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Grab Version
        run: |
          echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV
      
      - name: Grab Changelog
        run: |
          CHANGELOG=$(awk -v ver=$(cat version.txt) '/^## / { if (p) { exit }; if ($2 == ver) { p=1; next} } p' changelog.md)
          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: process.env.VERSION,
              name: process.env.VERSION,
              body: process.env.CHANGELOG,
              draft: true,
              prerelease: false
            })
            
            return data.id

  

  publish-release:
    runs-on: ubuntu-latest
    needs: create-release

    outputs:
      published_at: ${{ steps.publish-release.outputs.result }}
    
    steps:
      - name: Publish Release
        id: publish-release
        uses: actions/github-script@v6
        env:
          RELEASE_ID: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            const { data } = await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.RELEASE_ID,
              draft: false,
              prerelease: false
            })

            return data.published_at

  publish-update:
    runs-on: ubuntu-latest
    needs: [ create-release, publish-release ]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Create Update
        env:
          VERSION: ${{ needs.create-release.outputs.version }}
          CHANGELOG: ${{ needs.create-release.outputs.changelog }}
          PUBLISHED_AT: ${{ needs.publish-release.outputs.published_at }}
        run: node scripts/createUpdate.js

      - name: Publish Update
        run: |
          git config --global user.name 'Samuel Kopp'
          git config --global user.email 'azuryceo@users.noreply.github.com'
          git commit -am "published update"
          git push
