name: Publish Update

on:
  release:
  	types: [published]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Create Update
        run: node scripts/update.js

      - name: Publish Update
        run: |
          git config --global user.name 'Samuel Kopp'
          git config --global user.email 'azuryceo@users.noreply.github.com'
          git commit -am "published update"
          git push
